export { Emitter } from 'core/emitter'
export { Schedule } from 'core/schedule'
export { StoreEvent } from 'core/store'
export { getDataContext, getStoreContext, createProvider } from 'main/react-contexts'
export { useData, useStore, useStoreState } from 'main/react-hooks'
export { ReactStore } from 'main/react-store'
export { fullEqual, shallowEqual, deepEqual } from 'utils/comparators'
export { shallowClone, deepClone } from 'utils/replicators'
export { deepUpdate } from 'utils/updaters'

export type { Listener, EmitterOptions } from 'core/emitter'
export type { ScheduleOptions, ScheduleEvent, ScheduleTask } from 'core/schedule'
export type { Data, Store, StoreOptions, StoreTask, StoreTaskContext } from 'core/store'
export type { Class } from 'utils/declaration'
export type { ComparatorSupplier, Comparator } from 'utils/comparators'
